// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASgZrzQ0Mgqh1y0e_IPcyDxEowwyxZIfw',
    appId: '1:379364796982:web:621c2bb56122d6ec3cc697',
    messagingSenderId: '379364796982',
    projectId: 'vemjunto-f9f4d',
    authDomain: 'vemjunto-f9f4d.firebaseapp.com',
    databaseURL: 'https://vemjunto-f9f4d-default-rtdb.firebaseio.com',
    storageBucket: 'vemjunto-f9f4d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRvfG9G8QHSRGJQVRm1TDT1dErUJs3vyM',
    appId: '1:379364796982:android:5f9f5d51d331c6653cc697',
    messagingSenderId: '379364796982',
    projectId: 'vemjunto-f9f4d',
    databaseURL: 'https://vemjunto-f9f4d-default-rtdb.firebaseio.com',
    storageBucket: 'vemjunto-f9f4d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRc-XnmasFeR7Uj9rJJDO9FG6cTSUH3Hg',
    appId: '1:379364796982:ios:3bff1d8cf57ec5cf3cc697',
    messagingSenderId: '379364796982',
    projectId: 'vemjunto-f9f4d',
    databaseURL: 'https://vemjunto-f9f4d-default-rtdb.firebaseio.com',
    storageBucket: 'vemjunto-f9f4d.appspot.com',
    iosClientId: '379364796982-3q6lc1o8nmlvjjdi27o3cii2k889rqo6.apps.googleusercontent.com',
    iosBundleId: 'com.example.caronapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRc-XnmasFeR7Uj9rJJDO9FG6cTSUH3Hg',
    appId: '1:379364796982:ios:3bff1d8cf57ec5cf3cc697',
    messagingSenderId: '379364796982',
    projectId: 'vemjunto-f9f4d',
    databaseURL: 'https://vemjunto-f9f4d-default-rtdb.firebaseio.com',
    storageBucket: 'vemjunto-f9f4d.appspot.com',
    iosClientId: '379364796982-3q6lc1o8nmlvjjdi27o3cii2k889rqo6.apps.googleusercontent.com',
    iosBundleId: 'com.example.caronapp',
  );
}
